name = "RecursiveFiles"
uuid = "a2709a4f-6fc3-45eb-91be-3b3ed7e66148"
authors = ["Frank Platzek <frank.platzek@deltares.nl> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
